# Generated by Django 5.1.1 on 2024-11-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_capitulo_liberado_alter_modulo_liberado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitulo',
            name='liberado',
            field=models.BooleanField(default=False),
        ),
    ]
