# Generated by Django 5.1.1 on 2024-11-12 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_secao_liberada_secao_liberado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secao',
            old_name='liberado',
            new_name='liberada',
        ),
    ]
