# Generated by Django 5.1.1 on 2024-11-13 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_secao_descricao_remove_secao_nome_secao_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='secao',
            name='ehTeste',
            field=models.BooleanField(default=False),
        ),
    ]
