# Generated by Django 5.1.1 on 2024-12-10 22:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_secao_ehteste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atividadevideofrase',
            old_name='video_frase',
            new_name='video_atividade',
        ),
        migrations.CreateModel(
            name='AtividadeEscolhaCerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=999)),
                ('video_atividade', models.FileField(upload_to='uploads/videos/atividades', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('resposta', models.CharField(max_length=1)),
                ('alternativaA', models.CharField(max_length=255)),
                ('alternativaB', models.CharField(max_length=255)),
                ('alternativaC', models.CharField(max_length=255)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.secao')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeOrdenarPalavras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=999)),
                ('video_atividade', models.FileField(upload_to='uploads/videos/atividades', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('palavras', models.CharField(max_length=255)),
                ('resposta', models.CharField(max_length=255)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.secao')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeVerdadeiroOuFalso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=999)),
                ('video_atividade', models.FileField(upload_to='uploads/videos/atividades', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('resposta', models.CharField(max_length=1)),
                ('secao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.secao')),
            ],
        ),
    ]
