# Generated by Django 5.1.1 on 2024-12-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_video_frase_atividadevideofrase_video_atividade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividadeverdadeirooufalso',
            name='afirmacao',
            field=models.CharField(default='', max_length=255),
        ),
    ]
