# Generated by Django 5.1.1 on 2024-12-23 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_modulo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='usuario',
        ),
    ]
