# Generated by Django 5.1.1 on 2024-12-23 16:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_modulo_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capitulo',
            name='liberado',
        ),
        migrations.RemoveField(
            model_name='modulo',
            name='liberado',
        ),
        migrations.RemoveField(
            model_name='secao',
            name='liberada',
        ),
        migrations.CreateModel(
            name='ProgressoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo1', models.BooleanField(default=False)),
                ('modulo2', models.BooleanField(default=False)),
                ('modulo3', models.BooleanField(default=False)),
                ('capitulo1_modulo1', models.BooleanField(default=False)),
                ('capitulo2_modulo1', models.BooleanField(default=False)),
                ('capitulo1_modulo2', models.BooleanField(default=False)),
                ('capitulo2_modulo2', models.BooleanField(default=False)),
                ('capitulo1_modulo3', models.BooleanField(default=False)),
                ('capitulo2_modulo3', models.BooleanField(default=False)),
                ('secao1_capitulo1_modulo2', models.BooleanField(default=False)),
                ('secao2_capitulo1_modulo2', models.BooleanField(default=False)),
                ('teste_capitulo1_modulo2', models.BooleanField(default=False)),
                ('secao1_capitulo2_modulo2', models.BooleanField(default=False)),
                ('secao2_capitulo2_modulo2', models.BooleanField(default=False)),
                ('teste_capitulo2_modulo2', models.BooleanField(default=False)),
                ('secao1_capitulo1_modulo1', models.BooleanField(default=False)),
                ('secao2_capitulo1_modulo1', models.BooleanField(default=False)),
                ('teste_capitulo1_modulo1', models.BooleanField(default=False)),
                ('secao1_capitulo2_modulo1', models.BooleanField(default=False)),
                ('secao2_capitulo2_modulo1', models.BooleanField(default=False)),
                ('teste_capitulo2_modulo1', models.BooleanField(default=False)),
                ('secao1_capitulo1_modulo3', models.BooleanField(default=False)),
                ('secao2_capitulo1_modulo3', models.BooleanField(default=False)),
                ('teste_capitulo1_modulo3', models.BooleanField(default=False)),
                ('secao1_capitulo2_modulo3', models.BooleanField(default=False)),
                ('secao2_capitulo2_modulo3', models.BooleanField(default=False)),
                ('teste_capitulo2_modulo3', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
