# Generated by Django 5.1.1 on 2024-12-23 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_capitulo_liberado_remove_modulo_liberado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressousuario',
            name='capitulo1_modulo1',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='capitulo1_modulo2',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='capitulo1_modulo3',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='capitulo2_modulo1',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='capitulo2_modulo2',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='capitulo2_modulo3',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='modulo1',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='modulo2',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='modulo3',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='secao1_capitulo1_modulo1',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='secao1_capitulo1_modulo2',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='secao1_capitulo1_modulo3',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='secao1_capitulo2_modulo1',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='secao1_capitulo2_modulo2',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='secao1_capitulo2_modulo3',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='secao2_capitulo1_modulo1',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='secao2_capitulo1_modulo2',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='secao2_capitulo1_modulo3',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='secao2_capitulo2_modulo1',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='secao2_capitulo2_modulo2',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='secao2_capitulo2_modulo3',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='teste_capitulo1_modulo1',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='teste_capitulo1_modulo2',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='teste_capitulo1_modulo3',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='teste_capitulo2_modulo1',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='teste_capitulo2_modulo2',
        ),
        migrations.RemoveField(
            model_name='progressousuario',
            name='teste_capitulo2_modulo3',
        ),
        migrations.AddField(
            model_name='progressousuario',
            name='capitulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.capitulo'),
        ),
        migrations.AddField(
            model_name='progressousuario',
            name='liberado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progressousuario',
            name='modulo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.modulo'),
        ),
        migrations.AddField(
            model_name='progressousuario',
            name='secao',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.secao'),
        ),
    ]
