# Generated by Django 5.1.1 on 2024-12-23 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_progressousuariocapitulos_progressousuariomodulos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressousuariocapitulos',
            name='capitulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.capitulo'),
        ),
        migrations.AlterField(
            model_name='progressousuariocapitulos',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modulo'),
        ),
    ]
