# Generated by Django 5.1.1 on 2024-12-24 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_progressousuariocapitulos_capitulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressousuariocapitulos',
            name='modulo',
        ),
        migrations.RemoveField(
            model_name='progressousuariosecoes',
            name='capitulo',
        ),
        migrations.RemoveField(
            model_name='progressousuariosecoes',
            name='modulo',
        ),
    ]
